apiVersion: apps/v1
kind: Deployment
metadata:
  name: polytalko-app-kubernetes-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polytalko-app-kubernetes
  template:
    metadata:
      labels:
        app: polytalko-app-kubernetes
    spec:
      containers:
        - name: polytalko-app-container
          image: chaykow/polytalko-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name:  polytalko-app-kubernetes-service
  namespace: default
spec:
  type: NodePort
  selector:
    app:  polytalko-app-kubernetes
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001